app = 'lingual-bio-api'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[build.settings]

[mounts]
  source = 'lingual_data'
  destination = '/data'

[env]
  OSA_DATA_DIR = '/data'
  OSA_LOGGING__LEVEL = 'DEBUG'
  OSA_CONFIG_FILE = '/app/config.yaml'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[http_service.checks]]
  interval = '30s'
  timeout = '10s'
  grace_period = '120s'
  path = '/api/v1/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048
